version: '3'
services:
  mysql:
    image: 'mysql/mysql-server:5.7'
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      bifrost:
        ipv4_address: "10.1.1.2"
  postgres:
    image: "postgres:13.3-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_DATABASE}'
    networks:
      bifrost:
        ipv4_address: "10.1.1.3"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  mongo:
    image: "arm64v8/mongo:latest"
    ports:
      - "27017:27017"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGODB_USERNAME: "${DB_USER}"
      MONGODB_PASSWORD: "${DB_PASSWORD}"
      MONGODB_DATABASE: "${DB_DATABASE}"
      MONGODB_ENABLE_DIRECTORY_PER_DB: "yes"
      MONGODB_DISABLE_SYSTEM_LOG: "false"
      MONGODB_SYSTEM_LOG_VERBOSITY: "4"
    networks:
      bifrost:
        ipv4_address: "10.1.1.4"
  redis:
    image: "redis:6.2.4-alpine"
    ports:
      - "6379:6379"
    networks:
      bifrost:
        ipv4_address: "10.1.1.5"
  elastic:
    image: "arm64v8/elasticsearch:8.4.1"
    ports:
      - "9200:9200"
    networks:
      bifrost:
        ipv4_address: "10.1.1.6"
  adminer:
    image: adminer
    ports:
      - 3030:8080
    networks:
      bifrost:
        ipv4_address: "10.1.1.10"
  surrealdb:
    image: surrealdb/surrealdb
    ports:
      - 4000:8000
    command: start
    networks:
      bifrost:
        ipv4_address: "10.1.1.7"
networks:
  bifrost:
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
      